### ISSUE TITLE
Автоматические размеры балуна?

### ISSUE THREAD

**Issue by dpmango** [yandex-maps-unofficial/vue-yandex-maps#13]
Что делать в случае динамического контента внутри балуна? 
Было бы неплохо автоматически считать размеры

<img width="257" alt="Снимок экрана 2022-10-10 в 15 58 12" src="https://user-images.githubusercontent.com/18535792/194871674-a6afd1db-37a4-4c02-aa71-4ebc4a2c7fea.png">

P.S. Успешно подключилось на nuxt3-rc, полет нормальный

**Comment by PNKBizz** [comment]
Давайте вместе подумаем как можно это реализовать )

**Comment by sergeev-vn** [comment]
Поддерживаю,  очень необходимая вещь, может быть кто-нибудь придумал костыль?)

**Comment by Ramsly** [comment]
Сделал через CSS

`.ymaps-2-1-79-balloon {
  width: 330px !important;
  min-height: auto !important;
}` 

Костыль, но полет нормальный

**Comment by sergeev-vn** [comment]
> Сделал через CSS
> `.ymaps-2-1-79-balloon { width: 330px !important; min-height: auto !important; }`
Лично у меня не работает(

Высота для класса yandex-balloon обязательна, а плагин в свою очередь устанавливает по ней фиксированную высоту на обёртку балуна. Если не задавать, будет сплющенная высота как в первом посте. min-height в .ymaps-2-1-79-balloon даёт никакого результата

**Comment by Ramsly** [comment]
Странно, у меня все работает. Да есть проблема, когда контента внутри балуна нет, то балун будет сплюснутым. Но это хоть какой-то выход из положения)

**Comment by unn3daby** [comment]
> Странно, у меня все работает. Да есть проблема, когда контента внутри балуна нет, то балун будет сплюснутым. Но это хоть какой-то выход из положения)
> 
> > > Сделал через CSS
> > > `.ymaps-2-1-79-balloon { width: 330px !important; min-height: auto !important; }`
> > 
> > 
> > Лично у меня не работает(
> > Высота для класса yandex-balloon обязательна, а плагин в свою очередь устанавливает по ней фиксированную высоту на обёртку балуна. Если не задавать, будет сплющенная высота как в первом посте. min-height в .ymaps-2-1-79-balloon не даёт никакого результата

Костыль тоже не работает(

**Comment by Ramsly** [comment]
`<style lang="scss">
* {
  font-family: Helvetica, sans-serif;
  font-size: 1em;
}

.ymaps-2-1-79-balloon {
  width: 330px !important;
  min-height: auto !important;
}

.ymaps-2-1-79-balloon__content > ymaps {
  width: 100% !important;
  height: 100% !important;
}
</style>`

Полный код стилей для балунов 

@unn3daby 
@sergeev-vn

**Comment by daniluk4000** [comment]
Реализовано в 2.0, теперь размеры задаёт разработчик просто в стилях
