### ISSUE TITLE
Возможность расширить диапазон ожидания загрузки карт яндекса

### ISSUE THREAD

**Issue by vermorag** [yandex-maps-unofficial/vue-yandex-maps#147]
### Опишите, какую проблему вы хотите решить

Иногда ловим `YandexMapException: Was not able to wait for map initialization in waitTillMapInit.`в разных окружениях. В https://github.com/yandex-maps-unofficial/vue-yandex-maps/blob/master/packages/vue-yandex-maps/src/composables/utils/map.ts#L60 время ожидания задается статично - 5 сек, яндекс не всегда успевает за него подгрузиться.
![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/25276845/de31616e-36cb-4de6-94c1-de923e659831)

### Альтернативы

Самый простой вариант - дать возможность этот параметр передать при инициализации, чтобы для нужного окружения я мог прописать ждать не 5 сек, а 10 сек (а по умолчанию было бы 5), к примеру. Выглядит как костыль, но других предложений пока нет.

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я готов(а) помочь с имплементацией этого улучшения

**Comment by daniluk4000** [comment]
Согласен. И добавить возможность полностью отключать этот таймер ожидания.

**Comment by vermorag** [comment]
Есть возможность это сделать, или проще попробовать мне и закинуть мр?

**Comment by daniluk4000** [comment]
Я сделаю в районе выходных) 

Для waitTillMapInit также добавлю отдельную настройку, там уже не для медленного интернета, а скорее для калькуляторов.

**Comment by daniluk4000** [comment]
Можете глянуть https://github.com/yandex-maps-unofficial/vue-yandex-maps/pull/152

Смержить планирую завтра, либо сегодня поздно вечером

**Comment by daniluk4000** [comment]
Нашел интересный баг: если какой-то компонент висит на v-if, а вы его анмаунтите до полного рендера, он крашится

У вас случаем не такой кейс? Я словил на реальном проекте и исправлю.

**Comment by vermorag** [comment]
Нет, такой кейс не ловил.
