### ISSUE TITLE
Установка библиотеки ломает типы @vue/runtime-core

### ISSUE THREAD

**Issue by NickRisinger** [yandex-maps-unofficial/vue-yandex-maps#148]
### Версия библиотеки

2.0.0-rc.9

### Как воспроизвести

Задать декларацию типов для @vue/runtime-core

`
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $tv: <T>(value: T | undefined, defaultValue?: string) => string | T;
  }
}
`

Установить библиотеку: yarn add vue-yandex-maps@next

Запустить: yarn type-check

### Опишите проблему

Перестает видеть типы @vue/runtime-core

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
@NickRisinger подскажите пожалуйста, что делает команда yarn type-check?

И покажите ваш tsconfig.json.

**Comment by daniluk4000** [comment]
И какая версия Vue?

**Comment by NickRisinger** [comment]
tsconfig:
`
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": [
    "src/types/env.d.ts", "src/types/*", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
  "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@yandex/ymaps3-types"
    ],
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"],
      "types/*": ["./src/types/*"]
    }
  }
}
`

Команда:
"type-check": "vue-tsc --noEmit -p tsconfig.app.json --composite false",

**Comment by daniluk4000** [comment]
Интересно! На Vue 3 никто не жаловался, и у нас работает. В целом под Vue 3 мы собираем Vite'ом.

Могу попросить сделать репозиторий, где я бы смог воспроизвести проблему? Я сам попробую, конечно, но вы бы очень помогли, сделав репозиторий с проблемой.

**Comment by daniluk4000** [comment]
@NickRisinger и еще вопрос

А у вас случаем версия vue-tsc не древняя? Были с ней проблемы у одного человека, решилось обновлением vue-tsc

**Comment by NickRisinger** [comment]
@daniluk4000, Попробовал обновить с 1.6.4 до 1.8.25, но проблема осталась

**Comment by daniluk4000** [comment]
> @daniluk4000, Попробовал обновить с 1.6.4 до 1.8.25, но проблема осталась

Печаль. Тогда жду репозиторий (вы его можете создать, например, как hello world vue и внести то, что у вас ломает TS). 

Если репы не будет, попытаюсь сам воспроизвести в выходные, но не факт, что получитсяю

**Comment by NickRisinger** [comment]
Я только что попробовал, воспроизвести в hello world vue, но там ничего не сломалось, теперь я сижу в непонимании

**Comment by daniluk4000** [comment]
> @daniluk4000, Я только что попробовал, воспроизвести в hello world vue, но там ничего не сломалось, теперь я сижу в непонимании

Ожидаемо, потому что пока что вы первый, у кого что-то ломается на вью3. 

Если хотите, можем в ~субботу созвониться с демонстрацией экрана, поищем ошибку, либо вы можете дать доступ к своему проекту (при наличии такой возможности) и я поищу её сам.

**Comment by NickRisinger** [comment]
@daniluk4000, Да, на счет созвониться в субботу было бы чудесно, но будет не удобно если окажется, что ошибка в чем то другом. Постараюсь найти проблему до субботы

**Comment by NickRisinger** [comment]
@daniluk4000, заметил момент, что при установки vue-yandex-maps ставится и @vue/runtime-core@3.3.13, попробовал поставить ее отдельно и убедился, что ошибку вызывает именно эта библиотека.

**Comment by daniluk4000** [comment]
> @daniluk4000, заметил момент, что при установки vue-yandex-maps ставится и @vue/runtime-core@3.3.13, попробовал поставить ее отдельно и убедился, что ошибку вызывает именно эта библиотека.

Скажите спасибо Яндексу:
![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/10450717/f47a2e04-d010-4a5a-b2ad-46faab6da6d1)

Я думаю, что знаю, в чем у вас проблема. Версии этого рантайма и вашего вью отличается. 

Вам нужно обновить локфайл. Вроде бы в npm это npm update делает...

Если не знаете, как обновлять командой, то:
- Удалите node_modules
- Удалите lock-файл
- Выполните npm install / yarn install (и тд)

Должно помочь

**Comment by NickRisinger** [comment]
@daniluk4000, спасибо, это помогло избавиться от ошибок указанных выше, но вызвало кучу ошибок связанных с @vue/runtime-core, буду разбираться дальше

**Comment by daniluk4000** [comment]
Ишью закрываю, так как исправить это на стороне библиотеки можно только одним способом: убрать типы Яндекса. Так как это не представляется правильным решением (по сути строгая типизация пропадет), делать это я не планирую. 

А вот на месте Яндекса я бы убрал эти типы реакта и вью, конечно. Напишу им может в форму обратной связи.

**Comment by daniluk4000** [comment]
Передал пожелание разработчикам Яндекса.

**Comment by daniluk4000** [comment]
@NickRisinger в новой версии @yandex/ymaps3-types Яндекс убрали типы runtime compiler. Для информации)
