### ISSUE TITLE
YandexMapException: mapRoot is undefined in setupMapChildren. This is likely Vue Yandex Maps internal bug.

### ISSUE THREAD

**Issue by mirikqq** [yandex-maps-unofficial/vue-yandex-maps#195]
### Версия библиотеки

2.0.0-rc.11

### Как воспроизвести

https://stackblitz.com/edit/github-fwudqb?file=app.vue
npm run dev, npm run dev --host
Консоль открыть.

### Опишите проблему

№ 1 Спам ошибок в консоле, ломается при использование npm/yarn dev --host флага.
№ 2 Не корректно импортирует VueYandexMap - 
![Снимок экрана 2024-01-23 в 21 29 02](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/148229590/f1610834-7851-468c-bfc5-dea920b2091b)
![Снимок экрана 2024-01-23 в 21 31 27](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/148229590/88a833d1-1e94-4dcf-877c-3d40dc39e355)

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Добрый вечер. Не везет мне со StackBlitz, вечно в нём какие-то проблемы. Поднял локально, воспроизвёл проблему.

1. Я дополню ошибку mapRoot. Сейчас она выглядит непонятно, но на самом деле проблема проста: все контролы работают исключительно внутри `<yandex-map-controls>`, вы же используете `YandexMapControl`. После изменения на Controls ошибка ушла и карта отрисовалась. Сообщение об ошибке постараюсь сделать более понятным.
2. Подключил `vue-tsc` и typescript: { typeCheck: true }, никакой ошибки не показалось. После этого из интереса открыл вместо Webstorm в VS Code, и вуаля

![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/10450717/f67ebb0b-064e-4eeb-a156-1206d156aa07)

![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/10450717/e992aee7-fc2e-4b5a-8428-65d62b7575a1)

Я из интереса поменял `export * from './namespace.ts';` на `export { VueYandexMaps } from './namespace.ts';` и Webstorm перестал ругаться. Не знаю, что ему там не нравится, но в следующем обновлении также исправлю.

**Comment by mirikqq** [comment]
> Добрый вечер. Не везет мне со StackBlitz, вечно в нём какие-то проблемы. Поднял локально, воспроизвёл проблему.
> 
> 1. Я дополню ошибку mapRoot. Сейчас она выглядит непонятно, но на самом деле проблема проста: все контролы работают исключительно внутри `<yandex-map-controls>`, вы же используете `YandexMapControl`. После изменения на Controls ошибка ушла и карта отрисовалась. Сообщение об ошибке постараюсь сделать более понятным.
> 2. Подключил `vue-tsc` и typescript: { typeCheck: true }, никакой ошибки не показалось. После этого из интереса открыл вместо Webstorm в VS Code, и вуаля
> 
> ![image](https://private-user-images.githubusercontent.com/10450717/299073503-f67ebb0b-064e-4eeb-a156-1206d156aa07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDMzMjAsIm5iZiI6MTcwNjA0MzAyMCwicGF0aCI6Ii8xMDQ1MDcxNy8yOTkwNzM1MDMtZjY3ZWJiMGItMDY0ZS00ZWViLWExNTYtMTIwNmQxNTZhYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIwNTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMjFlYjA2NTcwMGJkOGFkMjdiZDJmZmUyNWJlNTVkZTM3ZjMwZjg1MzJkZDFkYTg4Zjk3NTllMTRjMzJhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I175dsXY7urQOZB_6ITQKFr9d1clHWtjDudqQHHPmzk)
> 
> ![image](https://private-user-images.githubusercontent.com/10450717/299073781-e992aee7-fc2e-4b5a-8428-65d62b7575a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDMzMjAsIm5iZiI6MTcwNjA0MzAyMCwicGF0aCI6Ii8xMDQ1MDcxNy8yOTkwNzM3ODEtZTk5MmFlZTctZmMyZS00YjVhLTg0MjgtNjVkNjJiNzU3NWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIwNTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YzA0YmNlOWIzYmIyN2NjZTIxNDA1MTg4ODNlNGQwNjI2ODdhOGNlN2Y0MGY0YmY3NDdiMmExMjZmNmMzMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b0HVcmSZyJkfG7nxHRlApyZ94Yj8ih1GBIObRvsbuRc)
> 
> Я из интереса поменял `export * from './namespace.ts';` на `export { VueYandexMaps } from './namespace.ts';` и Webstorm перестал ругаться. Не знаю, что ему там не нравится, но в следующем обновлении также исправлю.

Пропсы в webstorm не работают кстати, в vscode не проверял.

**Comment by daniluk4000** [comment]
> Пропсы в webstorm не работают (автокомплиты) кстати, в vscode не проверял.

![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/10450717/7eebf87a-6b0f-4e8e-ae10-e600d53946cb)

![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/10450717/7e3b53be-243a-4847-b059-0b14b0c323f0)

![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/10450717/8e70c820-b900-45de-a1cd-4ee29b591438)

Шторм капризный. Проверьте на своем проекте:
- Что стоит последняя версия вью
- Если стоит, пересоберите локфайл
- Если не помогло, выберите в Typescript - "Bundled"
- Если используете WSL, убедитесь, что в TypeScript и Node.js выбрана нода из WSL

![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/10450717/d350a4db-c47d-4d30-9192-286bf62c02e3)

У меня всё ок в вашем reproduction

**Comment by daniluk4000** [comment]
![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/10450717/ee4715c9-101f-437c-89c5-35963850de68)

О, подарок в новом шторме

**Comment by mirikqq** [comment]
> ![image](https://private-user-images.githubusercontent.com/10450717/299943412-ee4715c9-101f-437c-89c5-35963850de68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjUxMjcsIm5iZiI6MTcwNjI2NDgyNywicGF0aCI6Ii8xMDQ1MDcxNy8yOTk5NDM0MTItZWU0NzE1YzktMTAxZi00MzdjLTg5YzUtMzU5NjM4NTBkZTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEwMjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMzIzYzc5ZTY5ZDgxNDZiMjViN2NkZmU4YWFmNTEyM2VlMzNiZDJlY2Q1ZDg5MzQ3MWJjZjIxYTFlOGNlZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.952UDERS8I6G7DwqyWwcQzp8FgvzykwMNoH79IIcoDw)
> 
> О, подарок в новом шторме

Реально подарки xD
