### ISSUE TITLE
YandexMapMarker

### ISSUE THREAD

**Issue by teleskop150750** [yandex-maps-unofficial/vue-yandex-maps#234]
### Версия библиотеки

2.0

### Как воспроизвести

.

### Опишите проблему

При масштабировании YandexMapMarker смещается от начальных координат

### Дополнительная информация

https://youtu.be/VaGbLc3iPKw

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Так Яндекс позиционирует маркеры в версии 3.0 по умолчанию.

Вы можете скорректировать это сами, либо воспользоваться настройкой position: https://yandex-maps-unofficial.github.io/vue-yandex-maps/components/marker.html#position

**Comment by teleskop150750** [comment]
Действительно (. Извините за беспокойство.

**Comment by daniluk4000** [comment]
Ничего страшного) Сами, когда нашли, не понимали, что происходит.
