### ISSUE TITLE
Clusterer, анимация Cluster, Markers

### ISSUE THREAD

**Issue by qubeek** [yandex-maps-unofficial/vue-yandex-maps#236]
### Версия библиотеки

2.0.0 (latest)

### Как воспроизвести

**При каких условиях проявляется проблема:**

- При событии drag end, когда завершено перемещение по карте
- При событии zoom

### Опишите проблему

Столкнулись с проблемой, что при попытке анимировать кластер происходит постоянный `onRender`, который пересобирает уже существующие кластеры, запуская анимацию по новой.

**Ожидаемое поведение:**

При движении по карте, если `Clusterer` отображает ранее скрытый кластер, при появлении кластер появляется с анимацией. 

**Текущее поведение:**

При любом обновлении позиции и зума происходит полный ререндер `Clusterer`, который запускает анимацию по новой.
В том случае, если покинуть зону видимости и вернуться в неё, то кластеры больше не обновляются.

**Возможные проблемы:**

Неправильное поведение _cachedEntities и _visibleEntities в используемой `@yandex/ymaps3-clusterer@0.0.1`

**Какие методы решения проблемы пробовали:**

- Перехват `onRender`
- Vue Transition
- CSS Animation (как в примере, через класс)
- Vue `v-memo`
- Vue key (component key)

### Дополнительная информация

https://codesandbox.io/p/sandbox/vue-yandex-maps-animation-issue-zhhqmv

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Возможно и косяк библиотеки. Посмотрю на неделе.

**Comment by daniluk4000** [comment]
@qubeek посмотрите, пожалуйста, как оно теперь работает тут: https://yandex-maps-unofficial.github.io/vue-yandex-maps/examples/objects/clusterer.html

Это то ожидаемое поведение, которого вы бы хотели?

**Comment by qubeek** [comment]
Добрый день, да, выглядит именно так. Большое спасибо!

**Comment by daniluk4000** [comment]
Всегда рад! Сейчас зарелижу.
