### ISSUE TITLE
Ошибка в получении props у объекта при клике на карту

### ISSUE THREAD

**Issue by Denisoov** [yandex-maps-unofficial/vue-yandex-maps#245]
### Версия библиотеки

2.0.0-rc.13

### Как воспроизвести

Чтобы воспроизвести ошибку, нужно повесить handle на клик по карте и обратиться к первому параметру "object" и достичь данных _props

### Опишите проблему

Property '_props' is protected and only accessible within class 'GenericEntity<Props, DefaultProps, Root>' and its subclasses.ts-plugin(2445)

А почему _props решили сделать protected, когда условно в аттрибут `settings` можно прокинуть propertyes разных данных. Если есть другой способ получить данные который заложены в маркеры, то подскажите как это сделать

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Скорее всего это на стороне Яндекса. Но вернусь попозже

**Comment by Denisoov** [comment]
@daniluk4000 Есть результаты по проблеме?

**Comment by daniluk4000** [comment]
Посмотрел. Тип задан как protected на стороне Яндекса. У вас есть несколько вариантов:
- Положить то, что вам нужно из пропсов, в properties маркера, после чего обратиться к этим properties
- Использовать ts-ignore и проигнорировать то, что тип является защищенным. Благо JS это вам позволит сделать

Я бы использовал первый вариант, второй скорее костыль, если без него никак (но я в этом сомневаюсь), то можно так.
