### ISSUE TITLE
Нельзя получить uri в ответе suggest

### ISSUE THREAD

**Issue by projct1** [yandex-maps-unofficial/vue-yandex-maps#252]
### Версия библиотеки

2.0.1

### Как воспроизвести

```javascript
await ymaps3.suggest({
    text: 'запрос',
    attrs: 'uri',
    bounds: [[37.180442, 55.454739], [38.048453, 56.008056]]
}
```

### Опишите проблему

Согласно [официальной документации](https://yandex.ru/dev/geosuggest/doc/ru/request#attrs), чтобы получить в ответе `uri`, в запросе нужно передать параметр `attrs: 'uri'`.
Но в типе `SuggestOptions` библиотеки, этот параметр отсутствует.

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Добрый день. Передал ошибку разработчикам Яндекса. Баг на их стороне. Пока что можете накинуть ts-ignore или написать свою type-safe обёртку. 

Вообще у них куча параметров геосаджеста отсутствует в типизации. Я уточню, фича это или нет. Атрибуты при этом явно работают))

**Comment by projct1** [comment]
> Пока что можете накинуть ts-ignore или написать свою type-safe обёртку.

Добрый день)
Ну так это не помогает, так как сам запрос строится на основе их `SuggestOptions`, мой переданный параметр `attr` не попадает в запрос :"(

**Comment by daniluk4000** [comment]
> > Пока что можете накинуть ts-ignore или написать свою type-safe обёртку.
> 
> Добрый день) Ну так это не помогает, так как сам запрос строится на основе их `SuggestOptions`, мой переданный параметр `attr` не попадает в запрос :"(

Упс, я не заметил :(

Тогда я подозреваю, что это фича. Но надеемся на лучшее. Можете закинуть им в форму обратной связи пожелание: https://yandex.ru/maps-api/support

**Comment by projct1** [comment]
> Тогда я подозреваю, что это фича.

да уж, что за фича такая)
в доках можно передавать `attr` и получать `uri`, а по факту нельзя?
только если напрямую самому составлять запрос...

**Comment by daniluk4000** [comment]
¯\_(ツ)_/¯

**Comment by Coroner1st** [comment]
Не путайте отдельный сервис Геосаджеста и встроенный в API 3.0 suggest(). Это разные продукты и возможности их методов могут и будут отличаться.

**Comment by projct1** [comment]
получается, в доках API 3 нету параметра, чтобы в ответ был включён uri:

![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/9752959/6220970e-4cb7-4ec7-b098-07c053ae3953)

тогда почему в доках в ответе он есть, а по факту его нет (пробовал разные запросы делать)
либо в каких он случаях может быть, так как стоит `uri?`?
в доках об этом не говорится :"(

![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/9752959/4c9cfd97-7de8-4617-88e2-550ba6bce170)

**Comment by Coroner1st** [comment]
Геосаджест может интегрироваться в API 3.0 постепенно, как поиск и прочие методы, ведь сервис только развивается. Есть вероятность, что в будущем все возможности Геокодера, Геосаджеста и API Маршрутизатора будут перенесены в API 3.0 в полном объёме, а часть документации по ответу сервиса проросла уже сейчас, как случайный анонс. Тогда стоит подождать.
А если решение нужно уже здесь и сейчас, можно использовать fetch() к самим сервисам.

**Comment by projct1** [comment]
спасибо вам за разъяснения, как-то не додумался даже)
поставил у себя тудушки
