### ISSUE TITLE
Следит ли yandex-map-marker

### ISSUE THREAD

**Issue by Denisoov** [yandex-maps-unofficial/vue-yandex-maps#262]
### Версия библиотеки

2.0.0-rc.13

### Как воспроизвести

Достаточно через v-for создать  список из `<yandex-map-marker>` после чего отфильтровать список маркеров и вернуть в исходное состояние списка, то выпадает ошибка в консоль
![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/48566682/607d5a39-f9e7-467a-b78b-1eb487512864)

Ошибка: 
![image](https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/48566682/b4c2603a-607b-464a-aea8-af5e2f5b33b1)

### Опишите проблему

Проблема обновления маркеров на карте при манипуляции с массивом данных о маркерах

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Здравствуйте. Мы точно так же используем маркеры и с ними всё хорошо.

На моей практике, такая ошибка может возникать, если недостаточно уникально указать ключ этим маркерам, после чего обновляется что-то, что не указано в ключе, и оно падает.

Яндекс выполняет некоторые манипуляции с DOM, которые Vue не очень нравятся, но правильно указанный ключ решает проблему. Попробуйте поиграться с key.

**Comment by Denisoov** [comment]
@daniluk4000 а может ли передача списка данных через props как-то афектить? Может подскажете BEST PRACTICS как лучше подать данные и стоит ли применить к ключу шаблонный литерал?

**Comment by Denisoov** [comment]
@daniluk4000 аа я кажись только сейчас понял в чем причина, это все дело в `wrapper-attrs`. Я там устанавливаю pointId, чтобы в будущем получать от события клика данные

**Comment by daniluk4000** [comment]
> @daniluk4000 а может ли передача списка данных через props как-то афектить? Может подскажете BEST PRACTICS как лучше подать данные и стоит ли применить к ключу шаблонный литерал?

Литерал применить можно, и перечислить там все параметры, которые могут изменяться. Я бы, кстати, еще добавил index, чтобы даже изменение порядков элементов вызывало ререндер. Это является плохой практикой, но может помочь именно тут.

Видел еще писали про wrapper attrs. Влиять не должно, но если влияет, пишите

**Comment by Denisoov** [comment]
@daniluk4000 да я попробовал добавить уникальность ключам и все заработало, спасибо за оперативность!
