### ISSUE TITLE
Есть ли возможность добавить слой пробок на карту?

### ISSUE THREAD

**Issue by roman-ananiev** [yandex-maps-unofficial/vue-yandex-maps#270]
### Опишите, какую проблему вы хотите решить

прочитал доку, не нашел способа добавить слой пробок 

### Ответы на вопросы

- [X] Я использую версию 2.x
- [ ] Я готов(а) помочь с имплементацией этого улучшения

**Comment by roman-ananiev** [comment]
> Я такого способа не знаю - а жаль, было бы круто!
> 
> Можете написать как пожелание Яндексу: https://yandex.ru/maps-api/support

вот подобный функционал на react https://pbe-react-yandex-maps.vercel.app/en/api/controls/traffic-control/

**Comment by daniluk4000** [comment]
> > Я такого способа не знаю - а жаль, было бы круто!
> > Можете написать как пожелание Яндексу: https://yandex.ru/maps-api/support
> 
> вот подобный функционал на react https://pbe-react-yandex-maps.vercel.app/en/api/controls/traffic-control/

Боюсь, это не из-за реакта: по ссылке используются Карты 2.1, в этой репе 3.0.

Вот данный функционал в их примере: https://yandex.ru/dev/maps/jsbox/2.1/traffic_provider/

В данный момент traffic provider отсутствует в Картах 3.0.

**Comment by daniluk4000** [comment]
Ну то есть перефразируя: вы можете использовать vue-yandex-maps 0.x/1.x и там, вероятно, сможете реализовать слой пробок, так как там именно что Карты 2.1. 

Как я часто люблю говорить: 3.0 удобнее для разработчика, круче для пользователя, но фич в них меньше
