### ISSUE TITLE
API 3.0 released

### ISSUE THREAD

**Issue by drev74** [yandex-maps-unofficial/vue-yandex-maps#29]
Migration needed as per [this](https://yandex.ru/dev/maps/jsapi/doc/3.0/upgrade/index.html)

**Comment by daniluk4000** [comment]
@drev74 Migration is in progress in https://github.com/PNKBizz/vue-yandex-map/pull/457

**Comment by daniluk4000** [comment]
Подробное описание миграции: https://github.com/PNKBizz/vue-yandex-maps/discussions/60

**Comment by daniluk4000** [comment]
https://yandex-maps-unofficial.github.io/vue-yandex-maps/
