### ISSUE TITLE
v-show on marker doesn't work

### ISSUE THREAD

**Issue by Ask1n** [yandex-maps-unofficial/vue-yandex-maps#304]
### Версия библиотеки

2.1.2

### Как воспроизвести

add v-show to YandexMapMarker

### Опишите проблему

after 2.1.1 v-show on marker component doesn't work 

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Hello there. I don't know if you know Russian so I'll keep it that way. 

This is intended for performance. What your solutions are:
- Use v-if
- Set some class and use CSS to hide block
- Use v-show inside marker, not on `<yandex-map-marker>` itself
