### ISSUE TITLE
Пропадают маркеры во время фильтрации

### ISSUE THREAD

**Issue by loveLightning** [yandex-maps-unofficial/vue-yandex-maps#313]
Не могу понять почему у меня пропадают маркеры во время фильтрации маркеров. Смотрю вы уже правили проблемы с исчезанием маркеров/кластеров, но по-моему проблема все еще осталась.   
У меня есть рабочий пример. Вы должны перейти по ссылке https://dev.tastycoffee.ru/partners-map?id=9a2030b6-7c1e-41a2-96cc-464d03a2ea6a&name=%D0%92%D0%B5%D1%80%D0%B0&desc=%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE+%D0%BA%D0%BE%D1%84%D0%B5  затем, обязательно установите city ижевск в locale storage. 
<img width="562" alt="image" src="https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/74300821/3d63c39f-4aa4-4884-8924-2cc0a4d19ea3">

После того как вы установили нужный город, перезагрузите сайт с ссылкой которую я скинул. Затем нажмите на кнопку назад в карточке кофейни, и почему то пропадает маркер на котором мы сейчас были. 
<img width="1282" alt="image" src="https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/74300821/6553adeb-ce74-404e-a5b2-e727a23f9691">
Что произошло потом
<img width="1272" alt="image" src="https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/74300821/3aef5778-a021-495a-b676-c6556576e77c">

Я дебажил свой код и не выявил никаких проблем со своей стороны. У меня как было 7 маркеров на карте так и осталось. Все ключи для маркеров уникальны, пробовал без ключей, то же самое. Но что самое главное маркеры есть в dom. Но на карте их нету. И при зуме/скролле они снова появляются на карте.  

Я так же прикрепил видео того, как пропадает маркеры/маркер.
https://www.icloud.com/iclouddrive/062mtK1lVajuORLytNDRMZQZQ#Screen_Recording_2024-06-17_at_6.09.48%E2%80%AFPM

 
Если что-то стало непонятно, то я готов помочь
Данная библиотека используется в production, и мне надо как можно скорее решить этот вопрос.

**Comment by daniluk4000** [comment]
Добрый вечер. Почему этого не происходит, если не выбрать Ижевск?

Я до пятницы не в городе. В целом я вам советую:
- Убедиться, что версия Карт и вью - последние
- Поиграться с key на v-for маркеров

А если ничего не поможет, дождаться меня. К этому времени очень хотелось бы, чтобы вы попытались воспроизвести проблему в чистом проекте и отправили мне код (репу или сандбокс), где я также смогу поиграться

**Comment by loveLightning** [comment]
Привет. Если не выбираем Ижевск, то мы перемещаемся в другой город, там уже новые маркеры. А так при выходе из карточки мы остаемся в том же городе, где и случается баг. С ключами я игрался, пытался без них. vue ставил последнюю версию. Проблема остается.  Воспроизведу проблему в течение 2 дней.

**Comment by loveLightning** [comment]
Создал репу с проблемой - https://github.com/loveLightning/vue-yandex-maps-hidden-markers
Еше раз напишу как увидеть проблему. 
1. заходим на http://localhost:3000/ 
2. Переключаем наш город на Ижевск, чтобы он хранился в localStorage. 
<img width="1437" alt="image" src="https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/74300821/9e7d72b1-8c07-47c8-8805-1bef3c9697d3">

3. Затем вставляем новую ссылку в url. http://localhost:3000/?id=ff663a6d-439f-4269-98b8-2c5aa7aef273
4. И нажимаем "Назад" в карточке кофейни и маркеры пропадают.

**Comment by daniluk4000** [comment]
Ух, ну и задачку вы мне задали)

1. По какой-то причине ref'ка телепортируется обратно в дерево Vue
2. Рефку надо переместить обратно. Метода для того, чтобы пере-задать элемент, у Яндекса нет
3. Пересоздавать на каждое обновление маркер не вариант - подохнем от перфоманс проблем

По итогу добавил микро-костыль, чтобы перемещать элемент обратно. Очень грустно, что у Яндекса нет норм метода под это, но что поделать. Фикс будет добавлен в 2.1.3!

P.S. Поправьте ворнинги Failed to resolve component, очень мешают))

**Comment by loveLightning** [comment]
Ух-ты, спасибо за быстрое решение проблемы.
