### ISSUE TITLE
Кажется иногда кластеры пропадают при фильтрации. 

### ISSUE THREAD

**Issue by sunsetikLover** [yandex-maps-unofficial/vue-yandex-maps#327]
### Версия библиотеки

2.1.3

### Как воспроизвести

1. Склонировать репу. Та же самая репа, я ее обновил.  
2. Скачать зависимости и запустить проект.
3. 
<img width="1440" alt="image" src="https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/74300821/3a94603a-a23d-460f-938f-f4208da1a379">

В списке городов есть Глазов. Перейти на него с любого другого города. В Глазове есть 2 маркера. Но они видны только если приблизить. (Количество маркеров может измениться, так как данные с нашего тестового бэка)

### Опишите проблему

Мы уже с вами общались в прошлом [issue](https://github.com/yandex-maps-unofficial/vue-yandex-maps/issues/313). 
Я изменил gridSize для кластера и они снова начали пропадать после фильтрации. 
 

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by sunsetikLover** [comment]
Так же бывает так, что кластер(ы) при фильтрации остаются на карте, когда их уже нету в массиве. А новые они как бы есть в массиве, но они не видны на карте. Может быть это как-то поможет

**Comment by sunsetikLover** [comment]
Если можно, не могли бы вы сообщить мне примерные сроки, когда мы можем ожидать исправление этой проблемы?

**Comment by daniluk4000** [comment]
> Если можно, не могли бы вы сообщить мне примерные сроки, когда мы можем ожидать исправление этой проблемы?

В эти выходные у меня вроде не планируются путешествия, поэтому вот в них займусь

**Comment by daniluk4000** [comment]
Еще мне кажется что вот это: https://github.com/yandex-maps-unofficial/vue-yandex-maps/issues/331 и этот баг связаны. И если я правильно вижу проблему, там все будет посложнее, чем я думал. Но посмотрим

**Comment by daniluk4000** [comment]
@sunsetikLover а из интереса, откатитесь на 2.1.0. Если не поможет, то 2.0.1. Интересно, насколько давно сломали

**Comment by sunsetikLover** [comment]
> @sunsetikLover а из интереса, откатитесь на 2.1.0. Если не поможет, то 2.0.1. Интересно, насколько давно сломали

 Потестил разные версии 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc.14.  Проблема с кластерами так же остается

**Comment by daniluk4000** [comment]
Ок, спасибо

**Comment by daniluk4000** [comment]
@sunsetikLover я не вижу в той репе обновления, но я сейчас сам поиграюсь с gridSize

**Comment by daniluk4000** [comment]
В общем походу это Яндекс. Ад какой-то. 

![image](https://github.com/user-attachments/assets/3679c396-524c-45d4-92a4-99b48c4514f1)

Айдишки выглядят ОЧЕНЬ странно. И если посмотреть в их код, все становится ясным как день

`String.fromCharCode(this._nextFeatureIndex),` - вот из этого генерится айди кластера. Эм? Как оно вообще работает после этого и генерит кластеры в разных местах? Наверное, я не до конца понимаю их задумку...

В общем, исправлено, буду туда айди сетать

**Comment by daniluk4000** [comment]
Просьба проверить в 2.1.4-beta.1

**Comment by sunsetikLover** [comment]
> Просьба проверить в 2.1.4-beta.1

Спасибо большое. Завтра посмотрю.

**Comment by daniluk4000** [comment]
Я вроде ваш проект потыкал, живой, но вы все равно отпишитесь. Я тоже на своем проекте проверю. Я каждый раз, когда трогаю кластер, что-нибудь отваливается, но, надеюсь, в этот раз пронесет

**Comment by sunsetikLover** [comment]
Посмотрел, вроде все круто работает. Если в будущем что-то будет не так, то напишу.
