### ISSUE TITLE
Кластер перестает реагировать на реактивное содержимое после ререндера

### ISSUE THREAD

**Issue by DmitryArkh** [yandex-maps-unofficial/vue-yandex-maps#331]
### Версия библиотеки

2.1.3

### Как воспроизвести

1. Добавить в слот \#cluster любое реактивное содержимое
2. Проверить обновление содержимого в кластерах
3. Вызвать ререндер кластера
4. Содержимое в кластере более не обновляется

https://github.com/yandex-maps-unofficial/vue-yandex-maps/assets/28262355/6a1a6da8-cbb3-4232-8b07-735b6d0dc9aa

### Опишите проблему

Хотел сделать динамическую привязку классов для кластеров, которые бы изменялись в зависимости от текущих bounds карты, но при ререндеринге кластеры замирают.

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by vicecitydeluxe** [comment]
https://github.com/user-attachments/assets/41aac402-6059-4eec-8ebd-e8305248b661
Та же проблема. На видео попытался показать:
в YandexMapClustererClusters чилды реактивно меняются, НО фактически мы видим старые ноды и компоненты. 

Дев тулзы изначально корректно опознают, что это именно наши "нужные" компоненты.
Далее, когда мы отдалим/приблизим (переиницализируем наполнение в YandexMapClustererClusters), 
дев тулзы видят вновь созданнеы компоненты как 0х0, то есть они где-то отрендерились, но их мы не видим, а видим старые соответственно. 
По какому приципу рендерятся старые, так и не понял. Пробовал лечить перерендером родителя (YandexMapClusterer) через key, но как вы понимаете, такая себе идея.

**Comment by daniluk4000** [comment]
Задачка-дискотека, спасибо.

Проблема вновь возникает из-за чудесного кэша Яндекса, но в https://github.com/yandex-maps-unofficial/vue-yandex-maps/issues/327 я научился им управлять.

Я выпущу бета версию в рамках этой задачи, просьба посмотреть, что стало лучше и не стало хуже

**Comment by daniluk4000** [comment]
Просьба проверить в 2.1.4-beta.1

**Comment by DmitryArkh** [comment]
Данная проблема решена, однако теперь кластеры почему-то начали улетать при зуме, position не переназначал

**Comment by daniluk4000** [comment]
> Данная проблема решена, однако теперь кластеры почему-то начали улетать при зуме, position не переназначал

Ну хоть что-то. Ща, секунду

**Comment by daniluk4000** [comment]
Я походу fallthrough атрибутов потерял. Поправлю, спасибки

**Comment by daniluk4000** [comment]
Выпустил 2.1.4-beta.2 с фиксом

**Comment by DmitryArkh** [comment]
Теперь все на своих местах. Если вдруг найду что-то еще отвалившееся, отпишу. Благодарю за оперативность
