### ISSUE TITLE
При переходе между картами в мобильной версии приложение падает в Vue2

### ISSUE THREAD

**Issue by daniluk4000** [yandex-maps-unofficial/vue-yandex-maps#338]
### Discussed in https://github.com/yandex-maps-unofficial/vue-yandex-maps/discussions/336

<div type='discussions-op-text'>

<sup>Originally posted by **Mereibek** July 13, 2024</sup>
Наш проект прописан на Vue 2, и мы активно используем мобильную версию.

В проекте есть две карты, каждая находится на разных страницах.
При переходе на вторую карту она падает с ошибками, ошибки указаны ниже
<img width="1342" alt="Снимок экрана 2024-07-13 в 20 53 01" src="https://github.com/user-attachments/assets/ebf694c2-4fd1-48fa-840b-ca33b89fdc26">

</div>

**Comment by daniluk4000** [comment]
Вот это у меня вообще никак не воспроизводится, и у меня нет идей, почему это может быть. Пока не буду закрывать, но жду репозиторий

**Comment by daniluk4000** [comment]
@Mereibek забыл тэгнуть

**Comment by Mereibek** [comment]
Этот issue можно закрывать - у нас просто был сервис из модалок (прописан с rxJS и использовал requestAnimationFrame), убрав его все заработало
