### ISSUE TITLE
Событие @trueBounds в YandexMapClusterer отдает ошибочный диапазон вхождений, если это один верхнеуровневый кластер

### ISSUE THREAD

**Issue by vicecitydeluxe** [yandex-maps-unofficial/vue-yandex-maps#340]
### Версия библиотеки

2.1.3

### Как воспроизвести

1) В слот #cluster добавить элементы, завязанные на данные с координатами, например:

const example = [{
    id: 1,
    coordinates: [37.295, 55.415],
},
    {
        id: 2,
        coordinates: [37.395, 55.415],
    },
    {
        id: 3,
        coordinates: [37.623, 55.752],
    },
]

2) Залогировать вывод диапазона значений

@trueBounds="range => exampleLogFn(range)"

3) В случае, когда у нас кластер из двух вхождений (или же допустим всего 7 объектов в example, а вхождений 5), то диапазон отдается корректно,
первое значение берется из clusterFeatures[index].clusterer.features[_firstIndexOfFeatures_].geometry.coordinates,
второе соответственно из clusterFeatures[index].clusterer.features[_lastIdexOfFeatures_].geometry.coordinates
т.е. все хорошо.

4) В случае, когда мы хотим увидеть коордианты трех вхождений у самого большого кластера, то получаем не ожидаемый результат:

Фактический результат:
 [**37.295**, _55.752_]
 [_37.623_, **55.415**]
Ожидаемый результат:
[37.295, 55.415]
 37.623, 55.752
 
Ниже прикреплю видео-демонстрацию

https://github.com/user-attachments/assets/8a751147-0741-4b5c-94b3-0850b29e8108

### Опишите проблему

Диапазон вхождений должен формироваться аналогично на верхнем уровне кластера, как и на более мелких уровнях.

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Подскажите, вы можете поискать ошибку в коде?

Я примерно понял проблему, но там алгоритм не должен как-то зависеть от размера кластера

**Comment by daniluk4000** [comment]
И реактивность у вас поправилась в бета сборке?

**Comment by vicecitydeluxe** [comment]
> И реактивность у вас поправилась в бета сборке?

Да, там все хорошо, видел механизм поменялся, спасибо большое!

**Comment by vicecitydeluxe** [comment]
> Подскажите, вы можете поискать ошибку в коде?
> 
> Я примерно понял проблему, но там алгоритм не должен как-то зависеть от размера кластера

У меня в коде или в коде исходника, не совсем понял?
В примере никак не мутирую данные, которые приходят из @trueBounds, они нужны просто чтобы выборку показать на основе вхождения. Так что ошибки на моей стороне не может быть, если я правильно понимаю...
А если в исходнике смотреть, то где именно?

**Comment by vicecitydeluxe** [comment]
> > > Подскажите, вы можете поискать ошибку в коде?
> > > Я примерно понял проблему, но там алгоритм не должен как-то зависеть от размера кластера
> > 
> > 
> > У меня в коде или в коде исходника, не совсем понял? В примере никак не мутирую данные, которые приходят из @trueBounds, они нужны просто чтобы выборку показать на основе вхождения. Так что ошибки на моей стороне не может быть, если я правильно понимаю... А если в исходнике смотреть, то где именно?
> 
> В исходнике
> 
>     * https://github.com/yandex-maps-unofficial/vue-yandex-maps/blob/master/packages/vue-yandex-maps/src/components/modules/clusterer/YandexMapClustererCluster.vue#L91
> 
>     * https://github.com/yandex-maps-unofficial/vue-yandex-maps/blob/520e4c4b974260bb61621ecf6636259fc431a9aa/packages/vue-yandex-maps/src/functions/calculations.ts#L29
> 
> 
> Репка если что без проблем поднимается, в примере ManyPoints есть я вывожу результат этих методов (yarn && yarn test:vue3 или nuxt3)

Попробовал так, вроде помогло, перепроверьте меня плз:
![Снимок экрана 2024-07-15 163402](https://github.com/user-attachments/assets/529e3416-16bc-49d2-8d48-394681d8caff)

**Comment by daniluk4000** [comment]
Ок, посмотрю вечеро

**Comment by daniluk4000** [comment]
Да, вроде бы всё ок
