### ISSUE TITLE
Ошибка в Nuxt3: ymaps3 is not defined

### ISSUE THREAD

**Issue by amdusias** [yandex-maps-unofficial/vue-yandex-maps#351]
### Версия библиотеки

2.1.4

### Как воспроизвести

Подключить модуль vue-yandex-maps в файле nuxt.config.ts, настроить в соответствии с документацией на сайте в разделе Устанновка(блок Nuxt 3)

[Установка](https://yandex-maps-unofficial.github.io/vue-yandex-maps/guide/vue3.html)

### Опишите проблему

Подключил все как нужно. Ключ API действующий. Ошибок подключения нет в консоли. Подключил стандартный компонент. Выдет две ошибки в консоли. На втором скрине указано где именно вызывается

![Screenshot_2](https://github.com/user-attachments/assets/c5f9dc57-b3f1-4ce2-b56d-05f3f43340b3)
![Screenshot_3](https://github.com/user-attachments/assets/fa51ea7f-eabb-48f7-848d-073d1b82d290)

Код компонента выглядит так:

![Screenshot_1](https://github.com/user-attachments/assets/14fb3a98-4543-4ff5-baf7-cc33b0ec47da)

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Добрый вечер. ClientOnly библиотеке нынче не нужен, ну да ладно. 

Посмотрите на вкладке сеть, точно скрипт подключается? Referrer указали в настройках ЛК Яндекса?

**Comment by amdusias** [comment]
> Добрый вечер. ClientOnly библиотеке нынче не нужен, ну да ладно.
> 
> Посмотрите на вкладке сеть, точно скрипт подключается? Referrer указали в настройках ЛК Яндекса?

Я подключаю версию 2 яндекс карт. Но ругается на ymaps 3 версии. Значит библиотека работает только с 3 версией получается?Ведь в новом API v3 там уже и ts поддерживается?

**Comment by daniluk4000** [comment]
> > Добрый вечер. ClientOnly библиотеке нынче не нужен, ну да ладно.
> > Посмотрите на вкладке сеть, точно скрипт подключается? Referrer указали в настройках ЛК Яндекса?
> 
> Я подключаю версию 2 яндекс карт. Но ругается на ymaps 3 версии. Значит библиотека работает только с 3 версией получается?Ведь в новом API v3 там уже и ts поддерживается?

Версия Яндекса не равна версии библиотеки - библиотека 2.х работает с Яндекс Картами 3.0, да. И все поддерживается, включая TS и SSR. 

Вы проверяли мое сообщение? Для работы с Яндекс 3.0 нужно указать Referrer, также на вкладке Сеть должно быть видно, что-то подключается или нет.

**Comment by lynx-r** [comment]
Нужно в Яндекс Кабинете разработчика в настройках ключа API указать Ограничение по IP-адресам или по HTTP Referrer. https://yandex.ru/dev/jsapi30/doc/ru/limit Без этих настроек он выдает Bad request – invalid api key

**Comment by amdusias** [comment]
> > > Добрый вечер. ClientOnly библиотеке нынче не нужен, ну да ладно.
> > > Посмотрите на вкладке сеть, точно скрипт подключается? Referrer указали в настройках ЛК Яндекса?
> > 
> > 
> > Я подключаю версию 2 яндекс карт. Но ругается на ymaps 3 версии. Значит библиотека работает только с 3 версией получается?Ведь в новом API v3 там уже и ts поддерживается?
> 
> Версия Яндекса не равна версии библиотеки - библиотека 2.х работает с Яндекс Картами 3.0, да. И все поддерживается, включая TS и SSR.
> 
> Вы проверяли мое сообщение? Для работы с Яндекс 3.0 нужно указать Referrer, также на вкладке Сеть должно быть видно, что-то подключается или нет.

В поддержке ответили что вместо localhost в HTTP Referrer указывает домен по типу dev.local или т.п. В принципе поправил все норм
