### ISSUE TITLE
Nuxt 3: ошибка в консоли "Error: vector: internal error"

### ISSUE THREAD

**Issue by svk-man** [yandex-maps-unofficial/vue-yandex-maps#358]
### Версия библиотеки

2.1.4

### Опишите проблему

На детальной странице товара есть возможность выбора его цвета. При клике по цвету осуществляется смена роута, подгрузка данных по товару и отрисовка данных.

На этой же странице размещён компонент карты.

Если быстро кликать по разным цветам, то спустя 10-20 таких кликов и подгрузок новых данных на страницу, в консоли появляется ошибка:

```
Error: vector: internal error
    at main.js:1:196016
    at j._emit (main.js:1:12370)
    at vector.js:1:338368
    at je.fire (vector.js:1:19640)
    at _onContextLost (vector.js:1:82927)
    at je.fire (vector.js:1:19640)
    at HTMLCanvasElement._contextLostListener (vector.js:1:95153)
```

Ссылается на:
1) https://yastatic.net/s3/front-maps-static/maps-front-jsapi-3/3.0.14536703/build/static/bundles/main.js
2) https://yastatic.net/s3/front-maps-static/maps-front-jsapi-3/3.0.14536703/build/static/bundles/vector.js

При этом сам компонент отображается корректно.

Компонент карты взят из [примера](https://yandex-maps-unofficial.github.io/vue-yandex-maps/guide/quickstart.html#%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B):

```
    <yandex-map
      v-model="map"
      :settings="{
        location: {
          center: [37.617644, 55.755819],
          zoom: 9,
        },
      }"
      width="100%"
      height="500px"
  >
    <yandex-map-default-scheme-layer/>
  </yandex-map>
  ```

### Дополнительная информация

nuxt: "3.12.2"

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Привет! Тоже замечал эту ошибку. По ощущениям, она ни на что не влияет. Почему происходит - идей нет никаких совершенно. Такое ощущение, что чисто на стороне Яндекса. 

Если найдете баг у нас - переоткройте. Но я прям не знаю, почему это может быть :(

**Comment by svk-man** [comment]
Хорошо, спасибо за ответ!
