### ISSUE TITLE
Диграммы в кластере

### ISSUE THREAD

**Issue by YaredFall** [yandex-maps-unofficial/vue-yandex-maps#365]
### Опишите, какую проблему вы хотите решить

Возможность использовать маркеры кластера в виде круговых диаграмм 

### Альтернативы

вручную строить диаграмму через CSS или с помощью svg, доставая данные из пропа слота кластера `clusterer.features`

### Ответы на вопросы

- [X] Я использую версию 2.x
- [ ] Я готов(а) помочь с имплементацией этого улучшения

**Comment by daniluk4000** [comment]
Фактически задача состоит из того, чтобы добавить в #cluster поддержку кастомных компонентов

**Comment by daniluk4000** [comment]
На данный момент из-за отсутствия такой опции в Яндексе - только вручную

Для решения масштабируемости кластера в целом создал https://github.com/yandex-maps-unofficial/vue-yandex-maps/issues/366
