### ISSUE TITLE
Не добавляется маркер на карту

### ISSUE THREAD

**Issue by shiryaev585** [yandex-maps-unofficial/vue-yandex-maps#378]
### Версия библиотеки

2.1.4

### Как воспроизвести

https://github.com/shiryaev585/zateiniki/tree/yandex-marker-bug

Запустить можно из ветки yandex-marker-bug

### Опишите проблему

Проект на Nuxt 3
Следуя документации, добавить макер на карту не получается. В консоли ошибка - YandexMapException: Was not able to inject valid map in injectMap. This is likely Vue Yandex Maps internal bug. 
Пробовал и yandex-map-default-marker и yandex-map-marker. Наличие lang="ts" у script'а никак не меняет ситуацию. Наличие/отсутствие обёртки client-only также ни на что не влияет. Сама карта рендерится нормально.

![200](https://github.com/user-attachments/assets/f2fed83f-d529-4fae-9e46-566a7d0fd93d)

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
Переместите yandex-map-default-marker внутрь yandex-map, пожалуйста)

**Comment by shiryaev585** [comment]
@daniluk4000  ))Спасибо огромное
