### ISSUE TITLE
Ошибка после build

### ISSUE THREAD

**Issue by SarkorbekA** [yandex-maps-unofficial/vue-yandex-maps#384]
### Версия библиотеки

2.1.4

### Как воспроизвести

https://github.com/SarkorbekA/artroom-2.0 тут находится проект

### Опишите проблему

![image](https://github.com/user-attachments/assets/01ff67f1-c2da-475c-962a-0e39263f7178)
происходит ошибка только после build, а в dev mode всё отлично работает, не могу понять в чём проблема

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by flyingdove** [comment]
У меня в Nuxt 3 точно такая же ошибка, только в dev mode. Карта не отображается(

**Comment by daniluk4000** [comment]
@SarkorbekA @flyingdove проверьте установку корректных Referrer в личном кабинете Яндекса. Это то, что вызывает эту ошибку в 90% случаев

**Comment by SarkorbekA** [comment]
@daniluk4000 Добрый вечер, спасибо что отозвались, когда работаю с localhost, а точнее ip-адрес 127.0.0.1, как правильно указывать
![image](https://github.com/user-attachments/assets/e3c73740-6e7e-4225-a758-36426b6c5015)
![image](https://github.com/user-attachments/assets/e0145b89-7e66-4483-9605-a5facf9e8f89)
я попробовал и с локального хоста, и с помощью ngrok, но никак не проходит, вабще как правильно указывать referer?

**Comment by daniluk4000** [comment]
Я указываю localhost
