### ISSUE TITLE
Ошибка: initializing Yandex Map with onComponentMount setting

### ISSUE THREAD

**Issue by flyingdove** [yandex-maps-unofficial/vue-yandex-maps#389]
### Версия библиотеки

2.1.4

### Как воспроизвести

Использовать минимальный пример.

### Опишите проблему

Вот такая ошибка вылазит на минимальном примере:

vue-yandex-maps.js?v=59c8e509:592 An error occured while initializing Yandex Map with onComponentMount setting
vue-yandex-maps.js?v=59c8e509:593 
Event {isTrusted: true, type: 'error', target: script#vue-yandex-maps, currentTarget: script#vue-yandex-maps, eventPhase: 2, …}
38
Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by kr1ke** [comment]
как это решилось? Тоже самое на Nuxt 3

**Comment by azsheishenov** [comment]
Нашли решение? 
Так же столкнулся с проблемой....

**Comment by daniluk4000** [comment]
Друзья, основное решение - проверить Referer у вашего токена. Если там нет (условного) localhost, поставить и подождать пару часов

**Comment by vermorag** [comment]
Ключевой момент - подождать именно от 1 часа (не смотря на то, что в доке яндекса говорится про 20 минут), если не заработало сразу. Очень много раз сталкивались с долгой прогрузкой прав для токенов.

**Comment by azsheishenov** [comment]
Заработало, спасибо!
