### ISSUE TITLE
Маркер не появляется

### ISSUE THREAD

**Issue by Marselkkk** [yandex-maps-unofficial/vue-yandex-maps#403]
### Версия библиотеки

2.1.4

### Как воспроизвести

![Screenshot_2](https://github.com/user-attachments/assets/603d3fb2-11f7-44ad-a8ba-1a0fa8d4e342)
![image](https://github.com/user-attachments/assets/55b8162a-db5d-4d55-a754-1dfe9d423bfa)

### Опишите проблему

Не отображаются маркеры на карте

### Дополнительная информация

Используется nuxt 3 и options api

### Ответы на вопросы

- [X] Я использую версию 2.x
- [X] Я поискал похожие ошибки и не нашел таковых

**Comment by daniluk4000** [comment]
![image](https://github.com/user-attachments/assets/3cd3fbf2-1788-47e5-beb4-198263bc86d1)

С проблемой это не связано, но так делать очень, тут нет контекста. Это не скрипт сетап

А вообще

https://yandex-maps-unofficial.github.io/vue-yandex-maps/components/layer-default-features.html
