### ISSUE TITLE
Балун в кластере

### ISSUE THREAD

**Issue by Irina2512** [yandex-maps-unofficial/vue-yandex-maps#51]
Для маркера можно использовать компонент в качестве балуна, а можно ли использовать компонент в качестве балуна для кластера? Есть ситуация когда 2 маркера находятся по одним координатам (в моем случае - это разные пункты самовывоза, которые могут быть расположены в одном помещении). И получается для маркера я могу использовать компонент, а для 2х маркеров в одной точке мне приходится рисовать еще раз этот компонент в свойствах маркера (balloonContentBody).
Вот пример: https://codesandbox.io/s/quizzical-mestorf-t80zcd?file=/src/App.vue

**Comment by Irina2512** [comment]
огромное спасибо)

**Comment by daniluk4000** [comment]
Реализовано в 2.0, включая маркеры с одинаковыми координатами
