### ISSUE TITLE
Темная тема для карты

### ISSUE THREAD

**Issue by Mahraway** [yandex-maps-unofficial/vue-yandex-maps#53]
При обращении к компоненту, было бы неплохо, если бы можно было передовать параметр theme для переключения на темную тему чтобы не изобреть всякие фильтры для карты или накладывать слои.   Что скажете? Может я просто не нашел как это уже реализовано?

```
<yandexMap
        :settings='{
           ...
          version: "2.1", // Версия Я.Карт
        }'
        :coordinates="coords"
        :zoom="10"
        :detailed-controls="dControls"
        :controls="controls"
    >
```

**Comment by PNKBizz** [comment]
А где вы нашли в API карт такую возможность? Не нашел в документации

**Comment by Mahraway** [comment]
`initMap() {
      ymaps.ready(() => {
        const map = new ymaps.Map("map", {
          center: [55.76, 37.64],
          zoom: 10,
          controls: [],
          theme: "islands#dark"
        });
      });
    }`

**Comment by PNKBizz** [comment]
Да, отлично. Добавлю в ближайшее время. Спасибо!

**Comment by zomkd** [comment]
@PNKBizz  приветствую! 
Хотел реализовать темную тему, но так и не обнаружил свойство theme в api карт.
Проверил в песочнице пример выше, свойство theme: "islands#dark" - не сработало. 
Вы проверяли? У вас получилось?

**Comment by zomkd** [comment]
Нашел способ сделать темную тему используя:

const layer = new YMapDefaultSchemeLayer({
          theme: "dark"
        });

**Comment by daniluk4000** [comment]
У этой ишью какое-то большое число посещений. Для информации: тёмная тема доступна в версии 2.0 как `<yandex-map :settings="{ theme: 'dark' }">`
