### ISSUE TITLE
Marker icon options not reactive

### ISSUE THREAD

**Issue by IgRich** [yandex-maps-unofficial/vue-yandex-maps#71]
[Sandbox](https://codesandbox.io/p/sandbox/cranky-chihiro-mt2cjs?file=/src/App.vue)

При изменении иконки/размера маркера, на карте старая висит. И вероятно на изменения options в принципе не реагирует.

**Comment by crocone** [comment]
Здесь реактивность точно не работает - нужно нативные использовать методы, но проблема в том что например у меня и нативные не работают. 
#73

**Comment by daniluk4000** [comment]
В 2.0 реализована реактивность
