### ISSUE TITLE
Изменение параметров маркера по клику. 

### ISSUE THREAD

**Issue by crocone** [yandex-maps-unofficial/vue-yandex-maps#73]
Что-то не пойму как менять параметры кастомных маркеров по клику. 
Посмотрел по документации - вроде все верно, ошибок не выдает, просто ничего не меняется. 

```
yaObjectManager.objects.events.add('click', (e) => { 
    e.get('target').options.set({
      iconImageSize: [50,50],
    });
    selectedPointId.value = e.get('objectId')
  })
```

**Comment by IgRich** [comment]
Я вот так костылем подпер пока что, вроде работает. В моем случае мне только иконку менять нужно, здесь я тупо сравниваю то что во vue-массиве вижу - `clusterPoints`, и то что на карте отображается `clusterMarkers`.
И если иконки не совпадают, то меняю их через `marker.options.set('iconImageHref', newPointIcon)`

```typescript
const clusterMarkers = this.map.geoObjects._parentArray.get(0).getGeoObjects() as any[]
clusterMarkers.forEach((marker, index) => {
  if (clusterPoints[index]) {
    const newPointIcon = clusterPoints[index].type === 'mst-point' ? POINT_ICON : INACTIVE_POINT_ICON
    const realPointIcon = marker.options.get('iconImageHref')
    if (realPointIcon !== newPointIcon) {
      marker.options.set('iconImageHref', newPointIcon)
    }
  }
})
```

**Comment by daniluk4000** [comment]
В 2.0 работает без костылей силами разработчика
